export const TOKEN_INTROSPECTOR = Symbol('TOKEN_INTROSPECTOR'); // Token để tiêm phụ thuộc cho trình kiểm tra token
export const REMOTE_AUTH_GUARD = Symbol('REMOTE_AUTH_GUARD'); // Token để tiêm phụ thuộc cho guard xác thực từ xa
export const MESSAGE_SERVICE = Symbol('MESSAGE_SERVICE'); // Token để tiêm phụ thuộc cho dịch vụ tin nhắn
export const EVENT_PUBLISHER = Symbol('EVENT_PUBLISHER'); // Token để tiêm phụ thuộc cho nhà xuất bản sự kiện
export const CACHE_SERVICE = Symbol('CACHE_SERVICE'); // Token để tiêm phụ thuộc cho dịch vụ cache
export const MONGO_SERVICE = Symbol('MONGO_SERVICE'); // Token để tiêm phụ thuộc cho dịch vụ MongoDB

export const USER_RPC = Symbol('USER_RPC'); // Token để tiêm phụ thuộc cho RPC người dùng
export const SHIFT_RPC = Symbol('SHIFT_RPC'); // Token để tiêm phụ thuộc cho RPC ca làm việc
export const LOYALTY_RPC = Symbol('LOYALTY_RPC'); // Token để tiêm phụ thuộc cho RPC khách hàng thân thiết
export const CATEGORY_RPC = Symbol('CATEGORY_RPC'); // Token để tiêm phụ thuộc cho RPC danh mục sản phẩm
export const PRODUCT_RPC = Symbol('PRODUCT_RPC');
export const VARIANT_RPC = Symbol('VARIANT_RPC');
export const OPTION_GROUP_RPC = Symbol('OPTION_GROUP_RPC');
export const OPTION_ITEM_RPC = Symbol('OPTION_ITEM_RPC');
export const PRODUCT_OPTION_CONFIG_RPC = Symbol('PRODUCT_OPTION_CONFIG_RPC');
export const COMBO_RPC = Symbol('COMBO_RPC');
export const COMBO_ITEM_RPC = Symbol('COMBO_ITEM_RPC');
export const SUPPLIER_RPC = Symbol('SUPPLIER_RPC');
export const INGREDIENT_RPC = Symbol('INGREDIENT_RPC');
export const UNIT_CONVERSION_RPC = Symbol('UNIT_CONVERSION_RPC');
export const INVENTORY_BATCH_RPC = Symbol('INVENTORY_BATCH_RPC');
export const RECIPE_RPC = Symbol('RECIPE_RPC');
export const IMPORT_INVOICE_RPC = Symbol('IMPORT_INVOICE_RPC');
export const IMPORT_INVOICE_DETAIL_RPC = Symbol('IMPORT_INVOICE_DETAIL_RPC');
export const PURCHASE_PROPOSAL_RPC = Symbol('PURCHASE_PROPOSAL_RPC');
export const PURCHASE_PROPOSAL_DETAIL_RPC = Symbol('PURCHASE_PROPOSAL_DETAIL_RPC');
export const STOCK_CHECK_RPC = Symbol('STOCK_CHECK_RPC');
export const STOCK_CHECK_DETAIL_RPC = Symbol('STOCK_CHECK_DETAIL_RPC');
export const ZONE_RPC = Symbol('ZONE_RPC');
export const TABLE_RPC = Symbol('TABLE_RPC');
export const RESERVATION_RPC = Symbol('RESERVATION_RPC');
export const CART_RPC = Symbol('CART_RPC');
export const CART_ITEM_RPC = Symbol('CART_ITEM_RPC');
export const CART_ITEM_OPTION_RPC = Symbol('CART_ITEM_OPTION_RPC');
export const VOUCHER_RPC = Symbol('VOUCHER_RPC');
export const ORDER_RPC = Symbol('ORDER_RPC');
export const ORDER_VOUCHER_RPC = Symbol('ORDER_VOUCHER_RPC');
export const ORDER_TABLE_RPC = Symbol('ORDER_TABLE_RPC');
export const ORDER_ITEM_RPC = Symbol('ORDER_ITEM_RPC');
export const ORDER_ITEM_OPTION_RPC = Symbol('ORDER_ITEM_OPTION_RPC');
export const PAYMENT_TRANSACTION_RPC = Symbol('PAYMENT_TRANSACTION_RPC');
export const INVOICE_RPC = Symbol('INVOICE_RPC');
export const IMAGE_RPC = Symbol('IMAGE_RPC');
