export const USER_REPOSITORY = Symbol('USER_REPOSITORY'); // Token để tiêm phụ thuộc cho repository người dùng
export const SHIFT_REPOSITORY = Symbol('SHIFT_REPOSITORY'); // Token để tiêm phụ thuộc cho repository ca làm việc
export const LOYALTY_REPOSITORY = Symbol('LOYALTY_REPOSITORY'); // Token để tiêm phụ thuộc cho repository khách hàng thân thiết
export const AUTH_SERVICE = Symbol('AUTH_SERVICE'); // Token để tiêm phụ thuộc cho service xác thực
export const USER_SERVICE = Symbol('USER_SERVICE'); // Token để tiêm phụ thuộc cho service người dùng
export const SHIFT_SERVICE = Symbol('SHIFT_SERVICE'); // Token để tiêm phụ thuộc cho service ca làm việc
export const LOYALTY_SERVICE = Symbol('LOYALTY_SERVICE'); // Token để tiêm phụ thuộc cho service khách hàng thân thiết
export const ACCESS_TOKEN_PROVIDER = Symbol('ACCESS_TOKEN_PROVIDER'); // Token để tiêm phụ thuộc cho service access token
export const REFRESH_TOKEN_PROVIDER = Symbol('REFRESH_TOKEN_PROVIDER'); // Token để tiêm phụ thuộc cho service refresh token
export const USER_MONGO_AUDIT_REPOSITORY = Symbol('USER_MONGO_AUDIT_REPOSITORY'); // Token để tiêm phụ thuộc cho repository audit người dùng
export const USER_MONGO_OTP_REPOSITORY = Symbol('USER_MONGO_OTP_REPOSITORY'); // Token để tiêm phụ thuộc cho repository otp người dùng