export const CATEGORY_REPOSITORY = Symbol('CATEGORY_REPOSITORY');
export const CATEGORY_SERVICE = Symbol('CATEGORY_SERVICE');
export const PRODUCT_REPOSITORY = Symbol('PRODUCT_REPOSITORY');
export const PRODUCT_SERVICE = Symbol('PRODUCT_SERVICE');
export const OPTION_REPOSITORY = Symbol('OPTION_REPOSITORY');
export const OPTION_SERVICE = Symbol('OPTION_SERVICE');
export const PRINTER_REPOSITORY = Symbol('PRINTER_REPOSITORY');
export const PRINTER_SERVICE = Symbol('PRINTER_SERVICE');